### PR TITLE
Java wrapper for Libwally

### PR DESCRIPTION
**Pull request by jollyjoker992**
This PR adds wrapper for libwally in Java. This supports following wrappers:

- [x] Address
- [x] Bip32
- [x] Bip39
- [x] Script
- [x] PSBT
- [x] Transaction

### CODE REVIEW

**Comment by ChristopherA** [comment]
Seeking reviews from various Java experts  of this java wrapper of the powerful LibWally bitcoin library: @devrandom, @javiervargas, @msgilligan, @peacekeeper. Thanks!

**Comment by jollyjoker992** [comment]
@ChristopherA This PR is work-in-progress. I have to finish the psbt and transaction before need help to review.
Thank you.

**Comment by jollyjoker992** [comment]
@devrandom, @javiervargas, @msgilligan, @peacekeeper 
cc: @ChristopherA 
Hi! I already finished the first PR. It's really big PR so hopefully i can get help from you guys for the review. 
Thank you!

**Comment by msgilligan** [comment]
I took a quick look and at the high-level this looks like a reasonable approach that is well-implemented. There is a lot of code here and (especially because it is JNI) it could use a thorough review but I suspect that would take a dedicated day or two to complete.

I would also suggest using Github Actions to do CI builds as soon a possible.

The other thought that I had was that it would be nice if there were a set of Java interfaces that could be common between this implementation and other implementations like say **bitcoinj**. (I have been proposing steps in that direction for bitcoinj, but we haven't implemented them yet.)

**Comment by jollyjoker992** [comment]
@msgilligan Thanks for your quick review. It would be better if you incentively take effort to review this PR and make it to be usable soon, other improvements like Github action will be integrate later. 

This implementation follows the interface of [BCLibwallySwift](https://github.com/BlockchainCommons/BCLibwallySwift) that has been done before by @wolfmcnally. 

I think it would be better if we keep the same interface of them in the same community like BlockchainCommons for better and easier usage.

**Comment by ChristopherA** [comment]
I'm going to go ahead and merge this PR, though I believe due to the particular security risks of C<->Java that it should really have another level of review.

**Comment by ChristopherA** [comment]
In particular, as I understand it as I'm not an expert, the JNI uses strings in bridged function prototypes to C so you lose type checking at compile time, which means that review of this code is even more important. There may be other areas that need significant investigation.

/cc @msgilligan @devrandom @peacekeeper — what other particular security issues for C/C++ -> Java wrappers should we be careful we check off?

**Pull request merged**
